// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/mzfarshad/music_store_api/internal/adapter/repository"
	"github.com/mzfarshad/music_store_api/internal/application"
	"github.com/mzfarshad/music_store_api/internal/application/admin"
	"github.com/mzfarshad/music_store_api/internal/application/customer"
)

// Injectors from wire.go:

func NewContainer() (*application.Container, error) {
	db, err := repository.NewPostgresConnection()
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepo(db)
	adminUseCase := admin.NewUserService(userRepository)
	customerUseCase := customer.NewAuthService(userRepository)
	userCustomerUseCase := customer.NewUserService(userRepository)
	container := application.NewContainer(adminUseCase, customerUseCase, userCustomerUseCase)
	return container, nil
}
